### PR TITLE
Update Attendance.txt

### PR DESCRIPTION
**Pull request by dimashka951**

### CODE REVIEW

**Review by ymamahama — COMMENTED** [review]
Change the paragraphs

**Review by Endzior16 — DISMISSED** [review]
it's good

**Review by realyea — DISMISSED** [review]
looks good for me

**Review by kacper7x — APPROVED** [review]

**Review by kacper7x — APPROVED** [review]

**Review by kacper7x — DISMISSED** [review]

**Review by Majuchaa2115 — DISMISSED** [review]

**Review by D3ONISIO — APPROVED** [review]
nice

**Review by kacper7x — APPROVED** [review]

**Pull request merged**
