### PR TITLE
Update Attendance.txt

### PR DESCRIPTION
**Pull request by stachuu9777**
please check my changes  
@realyea

### CODE REVIEW

**Comment by stachuu9777** [comment]
please check my changes
@realyea
@kacper7x 
@Endzior16 
@D3ONISIO

**Review by realyea — APPROVED** [review]
looks good

**Review by Endzior16 — APPROVED** [review]
it's good

**Review by kacper7x — APPROVED** [review]

**Review by kacper7x — APPROVED** [review]

**Review by kacper7x — APPROVED** [review]

**Review by kacper7x — APPROVED** [review]

**Review by kacper7x — APPROVED** [review]

**Review by D3ONISIO — DISMISSED** [review]
git, ale musisz dodac swoje inne obecnosci bo slabo ze prawie za caly semestr byles tylko 2 dni

**Review by Endzior16 — APPROVED** [review]
it's good

**Review by realyea — APPROVED** [review]
looks good

**Review by ymamahama — APPROVED** [review]

**Review by kacper7x — APPROVED** [review]

**Pull request merged**
